server:
  port: 8079

# MyBatis\u914D\u7F6E
mybatis:
  # \u914D\u7F6Emapper\u7684\u626B\u63CF\uFF0C\u627E\u5230\u6240\u6709\u7684mapper.xml\u6620\u5C04\u6587\u4EF6
  mapperLocations: classpath*:Mappers/**/*-Mapper.xml
  #\u6307\u5B9A\u5B9E\u4F53\u7C7B
  type-aliases-package: com.example.github.Entity
  configuration:
    #\u5F00\u542F\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true

#\u6570\u636E\u5E93\u8FDE\u63A5
spring:
  datasource:
    url: jdbc:mysql://94.191.50.122:3306/spring_database?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    name: root
    password: Asd159752
    driver-class-name: com.mysql.cj.jdbc.Driver

